services:
  php-apache:
    image: php:8.3-apache
    container_name: php-apache-container
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      /bin/bash -c "composer install && apache2-foreground"
volumes: {}